### ISSUE TITLE
Would compression help much/any on the allowed content length?

### ISSUE THREAD

**Issue by salamanders** [graphicore/urlHosted#1]
Google recently released a better lossless alternative https://www.npmjs.com/package/brotli - would having the option to compress the data on the URL allow for more to fit into what the URL shorteners can handle?

**Comment by graphicore** [comment]
Oh, cool I did not know that they brought it to JavaScript. Did you try it in a browser?

BTW I do compression already, happens here  https://github.com/graphicore/urlHosted/blob/master/lib/sAndD.js using the deflate method of pako (like zlib) https://github.com/nodeca/pako

Brotli is probably a bit better. I did not measure the effect that compression has; thus to answer your question: I don't know but I assume that compression makes the URLs shorter :-)
